# Generated by Django 4.2.6 on 2024-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='default_profile.jpg', upload_to='profile'),
        ),
    ]
